"""add user_id column

Revision ID: 46074c9384a3
Revises: 982a50239115
Create Date: 2023-11-19 17:42:51.004605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46074c9384a3'
down_revision: Union[str, None] = '982a50239115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sittings', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sittings_user_id'), 'sittings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sittings_user_id'), table_name='sittings')
    op.drop_column('sittings', 'user_id')
    # ### end Alembic commands ###
