"""create sittings table

Revision ID: 69ef8b26003a
Revises: 
Create Date: 2023-11-19 15:06:47.426136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ef8b26003a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sittings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('duration_m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sittings_id'), 'sittings', ['id'], unique=False)
    op.create_index(op.f('ix_sittings_user_id'), 'sittings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sittings_user_id'), table_name='sittings')
    op.drop_index(op.f('ix_sittings_id'), table_name='sittings')
    op.drop_table('sittings')
    # ### end Alembic commands ###
