"""rename user_id into chat_id

Revision ID: 982a50239115
Revises: 69ef8b26003a
Create Date: 2023-11-19 16:46:38.147653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982a50239115'
down_revision: Union[str, None] = '69ef8b26003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sittings', sa.Column('chat_id', sa.String(), nullable=True))
    op.drop_index('ix_sittings_user_id', table_name='sittings')
    op.create_index(op.f('ix_sittings_chat_id'), 'sittings', ['chat_id'], unique=False)
    op.drop_column('sittings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sittings', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sittings_chat_id'), table_name='sittings')
    op.create_index('ix_sittings_user_id', 'sittings', ['user_id'], unique=False)
    op.drop_column('sittings', 'chat_id')
    # ### end Alembic commands ###
